### ISSUE TITLE
TypeError: can't convert np.ndarry of type numpy.object_

### ISSUE THREAD

**Issue by Leeway2ZC** [isaacveg/FLamingo_examples#1]
在生成数据文件时，在dataset_utils文件中，数据集文件0.npz用np.savez_compressed(f, data=train_dict)保存，只有一个键data。在读取数据文件时，在data_utils.py文件中，y_train = torch.Tensor(data['targets']).type(torch.int64)，这样不会报错吗？

generate_cifar10.py
save_file(config_path, train_path, test_path, train_data, test_data, num_clients, num_classes, statistic, niid, balance, partition)

dataset_utils.py
def save_file(config_path, train_path, test_path, train_data, test_data, num_clients, 
                num_classes, statistic, niid=False, balance=True, partition=None):
	...
    for idx, train_dict in enumerate(train_data):
        with open(train_path + str(idx) + '.npz', 'wb') as f:
            np.savez_compressed(f, data=train_dict)

data_utils.py
def create_dataset_instance(rank, dataset_type, data_dir, train_test):
    ...
    y_train = torch.Tensor(data['targets']).type(torch.int64)

**Comment by isaacveg** [comment]
你好。最新的版本FLamingo尚未打包，可以使用最新的[FLamingo_datasets](github.com/isaacveg/FLamingo_datasets)和[FLamingo](github.com/isaacveg/FLamingo)。在最新版FLamingo_datasets中gen_cifar10.py已经修改了这个问题
